# Generated by Django 4.2.11 on 2025-03-14 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewinstance',
            name='last_executed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crewinstance',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='idle', max_length=20),
        ),
        migrations.AlterField(
            model_name='crewinstance',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration including routing and state management for flows'),
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='crew.crewinstance')),
            ],
        ),
    ]
